import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../layout/layout'
import Test1 from './test/test1'
import Test2 from './test/test2'
import Test3 from './test/test3'
import Test4 from './test/test4'
import Test5 from './test/test5'

const Home = () => {
  return (
    <div className={styles.container}>
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <Test1></Test1>
      <Test2></Test2> {/*navの色を切り替えたい */}
      <Test3></Test3>
      <Test4></Test4> {/*navの色を切り替えたい */}
      <Test5></Test5>
    </Layout>
    </div>
  )
}

export default Home
